### ISSUE TITLE
Microcks Kafka truststore location

### ISSUE THREAD

**Issue by CROprogrammer** [microcks/microcks-ansible-operator#102]
### Describe the bug

When I use MicrocksInstall file:

```
apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcksinstall
spec:
  name: microcksinstall
  version: "1.7.0"
  microcks:
    replicas: 1
  postman:
    replicas: 1
  keycloak:
    replicas: 1
    install: true
    persistent: true
    volumeSize: 1Gi
  mongodb:
    replicas: 1
    install: true
    persistent: true
    volumeSize: 2Gi
  features:
    async:
      enabled: true
      defaultAvroEncoding: REGISTRY
      kafka:
        install: false
        url: microcks-cluster-kafka-bootstrap.microcks.svc.cluster.local:9093
        authentication:
          type: SSL
          truststoreType: PKCS12
          truststoreSecretRef:
            secret: microcks-cluster-cluster-ca-cert
            storeKey: ca.p12
            passwordKey: ca.password
          keystoreType: PKCS12
          keystoreSecretRef:
            secret: mtls-user
            storeKey: user.p12
            passwordKey: user.password
        schemaRegistry:
          url: https://apicurio-registry-ext-microcks.apps-crc.testing/apis/ccompat/v6
          confluent: true
```

I get error on my microcksintall pods:

`reason: CreateContainerConfigError
          message: secret "microcksinstall-kafka-truststore" not found`

Why is it looking for `microcksinstall-kafka-truststore` when I explicitly defined that `microcks-cluster-cluster-ca-cert` is the correct truststore?

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

operator

### Additional information

Local OpenShift, version 4.13.0, Kubernetes version: v1.26.3+b404935
