### ISSUE TITLE
Support for MongoDB secured connection

### ISSUE THREAD

**Issue by maximilianb28** [microcks/microcks-ansible-operator#108]
### Reason/Context

At this moment, the operator does not support ssl based connections to MongoDB

### Description

It would be good to have a support for providing SSL certificates when the MongoDB server is configured to only allow SSL connections. There is no way to provide a SSL certificate with the current configuration.

### Implementation ideas

The idea would be to pass the certificates in secrets as described below.

```yaml
mongodb:
  install: false
  uri: mongodb-svc:27017
  database: mongodb
  ssl:
    enabled: true
    certificateSecret: tls-certificate
    certificateAuthoritySecret: tls-ca-key-pair
```
