### ISSUE TITLE
Create Route with specific hostname

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks-ansible-operator#3]
For now, OpenShift routes are created using the default URI schema handled by the Router. 
That is because whenever I try adding a custom hostname in templates, OpenShift complains about not being possible to modify the `spec.host` field of Route for security reasons.

Will have to investigate...

**Comment by lbroudoux** [comment]
Just have to add those following `apiGroup` in role description and works like a charm!

```
- apiGroups:
  - route.openshift.io
  resources:
  - routes/custom-host
  verbs:
  - create
```
