### ISSUE TITLE
Update Kafka CR template

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks-ansible-operator#30]
With the latest versions of Strimzi, there is a new way to define the listeners for the Kafka custom resource. The current usage is still supported but will be removed in the future.

**Comment by lbroudoux** [comment]
Thanks Hugo. Could you put here the link to the doc explaining new syntax?

**Comment by hguerrero** [comment]
Here is the doc: https://strimzi.io/docs/operators/master/using.html#proc-config-kafka-str

New format:
```
    listeners: (8)
      - name: plain (9)
        port: 9092 (10)
        type: internal (11)
        tls: false (12)
        configuration:
          useServiceDnsDomain: true (13)
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication: (14)
          type: tls
      - name: external (15)
        port: 9094
        type: route
        tls: true
        configuration:
          brokerCertChainAndKey: (16)
            secretName: my-secret
            certificate: my-certificate.crt
            key: my-key.key
```
