### ISSUE TITLE
Operator requires Strimzi to be available

### ISSUE THREAD

**Issue by imod** [microcks/microcks-ansible-operator#66]
I would like microcks to connect to an existing Kafka instance, but I fail to get this working. I use the following CRD:

```
apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
spec:
  # Add fields here
  name: microcks
  version: "latest"
  microcks:
    replicas: 1
    url: microcks.192.168.49.2.nip.io
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
    url: microcks-keycloak.192.168.49.2.nip.io
    # serviceAccount: microcks-serviceaccount
    # serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
  features:
    repositoryFilter:
      enabled: true
      labelKey: app
      labelLabel: Application
      labelList: app,status
    async:
      enabled: true
      defaultBinding: KAFKA
      defaultFrequency: 10
      kafka:
        install: false
        url: "host.minikube.internal:29092"
```

But in the operator logs I see this: `Failed to find exact match for kafka.strimzi.io/v1beta2.Kafka`

Which I do understand: I don't have strimzi installed - I want microcks to use my own Kafka installation.
What am I doing wrong?
