### ISSUE TITLE
Resources not applied in mongodb

### ISSUE THREAD

**Issue by xacobecm** [microcks/microcks-ansible-operator#97]
### Describe the bug

When creating a MicrocksInstall resource with the following YAML:
```yaml
apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
  namespace: microcks
spec:
  keycloak:
    install: true
    persistent: true
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    volumeSize: 1Gi
  microcks:
    replicas: 1
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  mongodb:
    install: true
    persistent: true
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
    volumeSize: 2Gi
  name: microcks
  postman:
    replicas: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
  version: 1.7.0
```
All the pods came up with the limits and requests specified unless mongodb, which has the following resources:
```yaml
- resources:
        limits:
          memory: 512Mi
```

### Expected behavior

MongoDB having the limits and requests I specified in the MicrocksInstall

### Actual behavior

All the pods came up with the limits and requests specified unless mongodb, which has the following resources:
```yaml
- resources:
        limits:
          memory: 512Mi
```

### How to Reproduce?

1. Install Microcks 1.7.0 operator via OperatorHub in Openshift 4.
2. Create a MicrocksInstall resource with the YAML specified above.

### Microcks version or git rev

1.7.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

openshift operator

### Additional information

Openshift cluster version 4.11.26
